<script setup lang="ts">
</script>

<!-- I WANT THE BIO TO DISPLAY A FIELD OF TEXT THAT THE USER INPUTS, SO IT WILL BE BLANK OF COURSE WHEN NOTHING IS IN THERE. -->
<!-- THERE SHOULD BE A SMALL EDIT BUTTON THE USER SHOULD BE ABLE TO CLICK AND WHEN THEY CLICK IT, A MODAL POPS UP WITH A TEXT FIELD THAT ALLOWS THE USER TO ENTER THEIR BIO. -->
<!-- THE MODAL SHOULD HAVE A SAVE BUTTON THAT CLOSES THE MODAL AND SAVES THE USERS TEXT AND DISPLAYS IT IN THE BIO SECTION -->
<!-- THERE SHOULD ALSO JUST BE A "X" WITH A RED BACKGROUND TO CLOSE THE MODAL THAT DOESNT SAVE/UPDATE THE BIO OF THE USER. -->

<template>

  <div class="">
    <h3>bio is here</h3>
  </div>

</template>

<style scoped>
</style>