<script setup lang="ts">
</script>


<!-- I WANT TO MAKE IT SO THE USER HAS A PLACE TO WRITE 1-5 OF THEIR TOP GOALS -->
<!-- IT SHOULD START BLANK WITH JUST A BUTTON THAT SAYS "ADD GOAL" -->
<!-- WHEN THE USER SELECTS THE BUTTON, AN INPUT SHOULD DISPLAY, OR A MODAL THAT ALLOWS THE USER TO INPUT THEIR GOAL AND THEN THAT GOAL IS ADDED TO THE SECTION WITH AN EDIT AND A DELETE BUTTON -->
<!-- THE USER SHOULD BE ABLE TO LIST UP TO FIVE GOALS ONLY -->
<!-- IS A PROGRESS BAR POSSIBLE -->

<template>

  <div class="">
    <h1>users goals</h1>
  </div>

</template>

<style scoped>
</style>