<script setup lang="ts">
</script>

<!-- CREATE A "PERSONAL BEST SECTION". THE USER CAN PUT THEIR BEST RUNS< WORKOUTS, etc. -->
<!-- HAVE IT SO THE USER CAN SELECT WHICH PERSONALS BEST THINGS THEY WOULD LIKE TO DISPLAY UNDER THE PROFILE DIV, ABOVE THE USERS GOALS. PERSONAL BEST BENCH, SQUAT, FASTEST MILE, 40 YARD DASH, ETC... -->
<!-- HAVE IT TO THE ONLY ONES THAT SHOW ARE THE ONES THE USER HAS A VALUE IN, IF NO VALUE THEN THE TEXT FOR THAT PERSONAL BEST ISN'T EVEN SHOWN. 
  MAYBE HAVE LIKE AN "EYE" ICON THAT JUST ACTS AS A HIDE AND SHOW BUTTON EVEN IF THE USER HAS A VALUE ENTERED -->
<!-- BE SURE WHEN CREATING USER ON BACKEND, THEY HAVE ALL OF THE DIFFERENT WORKOUTS THAT A USER CAN SET A PERSONAL BEST TO. -->
<!-- MAYBE HAVE A SMALL EDIT BUTTON THAT DISPLAYS A MODAL OF ALL THE THINGS THE USER CAN SET A PERSONAL BEST TO. -->
<!-- OF COURSE MAKE IT SO THE EDIT BUTTON IS ONLY SHOWN ON YOUR PROFILE, WHEN ON ANOTHER USERS PROFILE BE SURE TO HAVE THE EDIT BUTTON HIDDEN -->

<template>

  <div class="">
    <h3>personal bests section</h3>
  </div>

</template>

<style scoped>
</style>