<script setup lang="ts">
</script>

<!-- SET UP FOR AN AREA FOR "SAVED ROUTES", MAYBE HAVE A MODAL POP UP TO SHOW THE USERS SAVED ROUTES, MAYBE EVEN JUST HAVE "SAVED ROUTES" BE A BUTTON UNDER THE USERS BIO THAT 
  ONCE CLICKS SHOWS A LIST OR OPENS A MODAL THAT DISPLAYS CLICKABLE LINKS THAT NAVIGATE TO /runningroutes AND DISPLAYS THAT ROUTE ON THE MAP(LOGIC TO BE DONE LATER) -->

<template>

  <div class="">
    <button>SAVED ROUTES</button>
  </div>

</template>

<style scoped>
</style>